services:
  app_encoder:
    build: 
      context: .
      dockerfile: src/encoding/Dockerfile
    container_name: encodear_archivos
    tty: true
    volumes:
      - ../../Ashurbanipal:/var/datos
      - ./output:/var/output
      - ./configuracion:/var/configuracion
      # - ./volumenes/treesitter_bindings:/var/lib/treesitter_bindings
    networks:
      - appnet
    command: ["./own_wiki", "-d", "/var/datos", "-c", "/var/configuracion", "-o", "/var/output"] 

  app_process:
    build: 
      context: .
      dockerfile: src/ejecucion/Dockerfile
    profiles:
      - frontend
    container_name: manejar_archivos
    depends_on:
      app_encoder:
        condition: service_completed_successfully
    tty: true
    ports:
      - "42069:42069"
    volumes:
      - ./src:/app
      - ./output:/var/output
      - ./configuracion:/var/configuracion
    networks:
      - appnet
    command: ["air", "-c", "ejecucion/.air.toml"] 

networks:
  appnet: