services:
  db_relacional:
    image: mysql:8
    container_name: mysql_db
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', '$MYSQL_ROOT_USER', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 1s
      timeout: 2s
      start_period: 3s
      retries: 5

    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - my-db-mysql:/var/lib/mysql
    networks:
      - appnet

  app_encoder:
    build: 
      context: .
      dockerfile: src/encoding/Dockerfile
    container_name: encodear_archivos
    depends_on:
      db_relacional:
        condition: service_healthy
    tty: true
    environment:
      # Necesario para mysql
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - ../../Ashurbanipal:/var/datos
      - ./output:/var/output
      - ./configuracion:/var/configuracion
      # - ./volumenes/treesitter_bindings:/var/lib/treesitter_bindings
    networks:
      - appnet
    command: ["./own_wiki", "-d", "/var/datos", "-c", "/var/configuracion", "-o", "/var/output"] 

  app_process:
    build: 
      context: .
      dockerfile: src/ejecucion/Dockerfile
    profiles:
      - frontend
    container_name: manejar_archivos
    depends_on:
      app_encoder:
        condition: service_completed_successfully
    tty: true
    environment:
      # Necesario para mysql
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "42069:42069"
    volumes:
      - ./src:/app
      - ./output:/var/output
      - ./configuracion:/var/configuracion
    networks:
      - appnet
    command: ["air", "-c", "ejecucion/.air.toml"] 

volumes:
  my-db-mysql: 

networks:
  appnet: