services:
  db_relacional:
    image: mysql:8
    container_name: mysql_db
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', '$MYSQL_ROOT_USER', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 1s
      timeout: 2s
      start_period: 3s
      retries: 5

    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - my-db-mysql:/var/lib/mysql
    networks:
      - appnet
  
  db_nosql:
    image: mongo:8.0
    container_name: mongo_db
    restart: always
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 2s
      start_period: 3s
      retries: 5

    environment:
      MONGO_INITDB_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - my-db-mongo:/data/db
    networks:
      - appnet

  app_encoder:
    build: .
    container_name: encodear_archivos
    depends_on:
      db_relacional:
        condition: service_healthy
      # db_nosql:
        # condition: service_healthy
    environment:
      # Necesario para mysql
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      # Necesario para mongodb
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_HOST: ${MONGO_HOST}
    volumes:
      - ../../Ashurbanipal:/var/lib/datos
      # - ./volumenes/treesitter_bindings:/var/lib/treesitter_bindings
    networks:
      - appnet
    command: ["./own_wiki", "-e", "/var/lib/datos"] 

  app_process:
    image: cosmtrek/air
    profiles:
      - frontend
    container_name: manejar_archivos
    working_dir: /app/codigo
    depends_on:
      app_encoder:
        condition: service_completed_successfully
    stdin_open: true 
    tty: true
    environment:
      # Necesario para mysql
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      # Necesario para mongodb
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_HOST: ${MONGO_HOST}
    ports:
      - "42069:42069"
    volumes:
      - ./src:/app/codigo
    networks:
      - appnet

volumes:
  my-db-mysql: 
  my-db-mongo: 

networks:
  appnet: