services:
  app_encoder:
    build: 
      context: .
      dockerfile: src/encoding/Dockerfile
    profiles:
      - preprocesar
    container_name: encodear_archivos
    tty: true
    volumes:
      - ../../Ashurbanipal:/var/datos
      - ../../Peque単a Biblioteca/.configuracion:/var/configuracion
      - ../../Peque単a Biblioteca:/var/output
    networks:
      - appnet
    command: ["./own_wiki", "-d", "/var/datos", "-c", "/var/configuracion", "-o", "/var/output"] 

  app_process:
    build: 
      context: .
      dockerfile: src/ejecucion/Dockerfile
    container_name: manejar_archivos
    depends_on:
      app_encoder:
        condition: service_completed_successfully
    tty: true
    ports:
      - "12345:12345"
    volumes:
      - ./src:/app
      - ../../Peque単a Biblioteca/.configuracion:/var/configuracion
      - ../../Peque単a Biblioteca:/var/output
    networks:
      - appnet
    command: ["air", "-c", "ejecucion/.air.toml"] 

volumes:
  my-db-mysql: 

networks:
  appnet: