services:
  db_relacional:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - appnet
  
  db_nosql:
    image: monto:8.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
      - config-db:/data/configdb

  app_encoder:
    build: .
    container_name: encodear_archivos
    depends_on:
      - db_relacional
      - db_nosql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    volumes:
      - ../../Ashurbanipal:/var/lib/datos
      - ./volumenes/output:/var/lib/output
    networks:
      - appnet
    command: ["./own_wiki", "-e", "/var/lib/datos", "/var/lib/output"] 

  app_process:
    build: .
    container_name: manejar_archivos
    depends_on:
      app_encoder:
        condition: service_completed_successfully
    stdin_open: true 
    tty: true
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    volumes:
      - ./volumenes/output:/var/lib/datos
    networks:
      - appnet
    command: ["./own_wiki", "-p", "/var/lib/datos"] 
volumes:
  my-db: 

networks:
  appnet:
